### ISSUE TITLE
Adding a locale?

### ISSUE THREAD

**Issue by remorse** [drmuey/p5-Locales#4]
Hi! I'd like to use `Locales` to replace `Text::Conjunct`, so that I can properly create a list of items in different languages. Unfortunately, one language I need to support probably isn't really in the CLDR — it's Haitian Creole. I have a language code for it (`ht`), but `Locales` doesn't recognize it.

Is there some way that I can somehow add a local stub for the language code, and just have the stuff needed to create the "and" list?

Thanks,
Ricky

**Comment by drmuey** [comment]
I'm so sorry I missed this @remorse !

It'd be as simple as creating `lib/Locales/DB/Language/ht.pm` and `lib/Locales/DB/Territory/ht.pm` (and if you want the javascript side of it, the ht.json files under `share/`). 

You could use the `en` files as a starting point or another one that is closer to `ht`.

**Comment by remorse** [comment]
Thanks for getting back to me -- I wound up using Locales to extract the information I needed from the CLDR for the various languages I was interested in, and then was able to add the information for `ht` in my own subset space.
